---
title: "04_Evidence-Based_Priors"
author: "Arthur M. Albuquerque"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: 
  html_document:
          code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
# Ensures the package "pacman" is installed
if (!require("pacman")) install.packages("pacman")

# p_load() installs (if necessary) and loads the following packages

pacman::p_load(tidyverse, # Data wrangling and plotting
               kableExtra, # To create tables
               ggdist, # To plot distributions
               here, # To find file paths within R project
               metafor # To create priors from meta-analysis
               )

```

```{r}
# Load data

d = read.csv((here("final_analyses", "output", "data", # file path
                   "respiratory-data.csv")),           # file name
             header = T)
d = d %>% 
  as_tibble() %>% 
  select(!starts_with("X")) 
```

```{r}
# Create different variables per subgroup

priors_simple_oxygen_raw =
  d %>%
  filter(
    trial != "RECOVERY",
    oxygen == "simple oxygen"
  )

priors_noninvasive_raw =
  d %>%
  filter(
    trial != "RECOVERY",
    oxygen == "non-invasive ventilation"
  )

priors_invasive_raw =
  d %>%
  filter(
    trial != "RECOVERY",
    oxygen == "invasive ventilation"
  )
```


# Mortality

<br>

**Regarding this outcome, negative risk differences mean benefit.**

```{r}
priors_simple_oxygen =
  rma(
    # Outcome
    measure = "RD", # risk difference
    
    # Tocilizumab group
    ai = events_toci,
    n1i = total_toci,

    # Control group
    ci = events_control,
    n2i = total_control,
    
    data = priors_simple_oxygen_raw %>% filter(outcome == "mortality"),

    slab = paste(trial),
    method = "REML"
  )

priors_noninvasive =
  rma(
    # Outcome
    measure = "RD", # risk difference
    
    # Tocilizumab group
    ai = events_toci,
    n1i = total_toci,

    # Control group
    ci = events_control,
    n2i = total_control,
    
    data = priors_noninvasive_raw %>% filter(outcome == "mortality"),

    slab = paste(trial),
    method = "REML"
  )

priors_invasive =
  rma(
    # Outcome
    measure = "RD", # risk difference
    
    # Tocilizumab group
    ai = events_toci,
    n1i = total_toci,

    # Control group
    ci = events_control,
    n2i = total_control,
    
    data = priors_invasive_raw %>% filter(outcome == "mortality"),

    slab = paste(trial),
    method = "REML"
  )
```

## Trials

# {.tabset .tabset-fade}

## Simple oxygen only {.panel-name}

```{r, fig.align='center', fig.height=4, fig.width=5}
forest(priors_simple_oxygen)
```

------------------------------------------------------------------------

## Non-invasive ventilation {.panel-name}
```{r, fig.align='center', fig.height=4, fig.width=5}
forest(priors_noninvasive)
```

------------------------------------------------------------------------

## Invasive mechanical ventilation {.panel-name}
```{r, fig.align='center', fig.height=4, fig.width=5}
forest(priors_invasive)
```

------------------------------------------------------------------------

# {-} 

## Priors

```{r}
## Extract mean and SD from rma() outputs

# Simple oxygen only
mean_prior_only = priors_simple_oxygen$beta
sd_prior_only = priors_simple_oxygen$se

# Non-invasive ventilation
mean_prior_noninvasive = priors_noninvasive$beta
sd_prior_noninvasive = priors_noninvasive$se

# Invasive mechanical ventilation
mean_prior_invasive = priors_invasive$beta
sd_prior_invasive = priors_invasive$se

table_prior =  tibble(
  
  "Subgroup" = c(
    "Simple oxygen only",
    "Non-invasive ventilation",
    "Invasive mechanical ventilation"
  ),
  
  "Number of trials" = c(
    priors_simple_oxygen_raw %>%
      filter(outcome == "mortality") %>%
      count() %>% pull(),
    priors_noninvasive_raw %>%
      filter(outcome == "mortality") %>%
      count() %>% pull(),
    priors_invasive_raw %>%
      filter(outcome == "mortality") %>%
      count() %>% pull()
  ),
  
  "Total number of patients" = c(
    priors_simple_oxygen_raw %>%
      filter(outcome == "mortality") %>%
      summarise(n = sum(total_control + total_toci)) %>% pull(),
    priors_noninvasive_raw %>%
      filter(outcome == "mortality") %>%
      summarise(n = sum(total_control + total_toci)) %>% pull(),
    priors_invasive_raw %>%
      filter(outcome == "mortality") %>%
      summarise(n = sum(total_control + total_toci)) %>% pull()
  ),
  
  "Mean RD" = c(
    round(mean_prior_only, 3),
    round(mean_prior_noninvasive, 3),
    round(mean_prior_invasive, 3)
  ),
  
  "SD" = c(
    round(sd_prior_only, 3),
    round(sd_prior_noninvasive, 3),
    round(sd_prior_invasive, 3)
  ),
  
  "Pr(< -5%)" = c(
    round(pnorm(-0.05, mean_prior_only, sd_prior_only), 2) * 100,
    round(pnorm(-0.05, mean_prior_noninvasive, sd_prior_noninvasive), 2) * 100,
    round(pnorm(-0.05, mean_prior_invasive, sd_prior_invasive), 2) * 100
  ),
  
  "Pr(< -2%)" = c(
    round(pnorm(-0.02, mean_prior_only, sd_prior_only), 2) * 100,
    round(pnorm(-0.02, mean_prior_noninvasive, sd_prior_noninvasive), 2) * 100,
    round(pnorm(-0.02, mean_prior_invasive, sd_prior_invasive), 2) * 100
  ),
  
  "Pr(< -1%)" = c(
    round(pnorm(-0.01, mean_prior_only, sd_prior_only), 2) * 100,
    round(pnorm(-0.01, mean_prior_noninvasive, sd_prior_noninvasive), 2) * 100,
    round(pnorm(-0.01, mean_prior_invasive, sd_prior_invasive), 2) * 100
  ),
  
  "Pr(< 0%)" = c(
    round(pnorm(0, mean_prior_only, sd_prior_only), 2) * 100,
    round(pnorm(0, mean_prior_noninvasive, sd_prior_noninvasive), 2) * 100,
    round(pnorm(0, mean_prior_invasive, sd_prior_invasive), 2) * 100
  ),
  
  "Pr(> 1%)" = c(
    round((1 - pnorm(0.01, mean_prior_only, sd_prior_only)), 2) * 100,
    round((1 - pnorm(0.01, mean_prior_noninvasive, sd_prior_noninvasive)), 2) * 100,
    round((1 - pnorm(0.01, mean_prior_invasive, sd_prior_invasive)), 2) * 100
  ),
  
  "Pr(> 2%)" = c(
    round((1 - pnorm(0.02, mean_prior_only, sd_prior_only)), 2) * 100,
    round((1 - pnorm(0.02, mean_prior_noninvasive, sd_prior_noninvasive)), 2) * 100,
    round((1 - pnorm(0.02, mean_prior_invasive, sd_prior_invasive)), 2) * 100
  ),
  
  "Pr(> 5%)" = c(
    round((1 - pnorm(0.05, mean_prior_only, sd_prior_only)), 2) * 100,
    round((1 - pnorm(0.05, mean_prior_noninvasive, sd_prior_noninvasive)), 2) * 100,
    round((1 - pnorm(0.05, mean_prior_invasive, sd_prior_invasive)), 2) * 100
  )
)

# Use kableExtra to have a nice table

table_prior %>% 
  kbl(booktabs = T, align = 'c') %>% 
  kable_styling(bootstrap_options = "striped", full_width = F) %>% 
  column_spec(9, bold = T, color = "#65A37E") %>%
  add_header_above(c(" " = 5,
                     "Probability of Benefit" = 4,
                     "Probability of Harm" = 3)) %>% 
  footnote(general = "RD = Risk Difference; SD = Standard Deviation")
```


```{r, fig.align='center', fig.height=3.5, fig.width=9, fig.cap="Interval bars depict 50% and 95% credible intervals"}
### Plotting
set.seed = 123 # set seed for reproducibility (rnorm())
n = 10e4 # sampling size

# Assure subgroup order
# https://stackoverflow.com/questions/12774210/
# how-do-you-specifically-order-ggplot2-x-axis-instead-of-alphabetical-order

level_order = c("Invasive mechanical ventilation",
                "Non-invasive ventilation",
                "Simple oxygen only")

# Generate random normal distributed samples

tibble(
  "Simple oxygen only" = rnorm(n,
                               mean = mean_prior_only,
                               sd = sd_prior_only
  ),
  "Non-invasive ventilation" = rnorm(n,
                                     mean = mean_prior_noninvasive,
                                     sd = sd_prior_noninvasive
  ),
  "Invasive mechanical ventilation" = rnorm(n,
                                            mean = mean_prior_invasive,
                                            sd = sd_prior_invasive
  )
) %>%
  
  # make it tidy for ggplot
  pivot_longer(
    cols = c("Simple oxygen only":"Invasive mechanical ventilation"),
    names_to = "dist", values_to = "samples"
  ) %>%
  
  # Plot!
  ggplot(aes(x = 100 * samples, y = factor(dist, level = level_order))) +
  stat_halfeye(aes(fill = stat(x < 0)),
    .width = c(0.5, 0.95)
  ) +
  scale_fill_manual(values = c("gray80", "#65A37E")) +
  labs(x = "\nRisk difference (%)", y = "") +
  scale_x_continuous(breaks = seq(from = -20, to = 25, 5)) +
  scale_y_discrete(
    expand = c(0, .2)
  ) +
  theme(
    axis.ticks.x = element_blank(),
    axis.ticks.y = element_blank(),
    panel.background = element_blank(),
    panel.grid.major.x = element_line(color = "gray80", size = 0.3),
    legend.position = "none",
    plot.margin = margin(10, 10, 25, 10)
  ) +
  coord_cartesian(xlim = c(-20, 25))
```

# Hospital discharge

<br>

**Regarding this outcome, positive risk differences mean benefit.**

```{r}
priors_simple_oxygen =
  rma(
    # Outcome
    measure = "RD", # risk difference
    
    # Tocilizumab group
    ai = events_toci,
    n1i = total_toci,
    
    # Control group
    ci = events_control,
    n2i = total_control,
    
    data = priors_simple_oxygen_raw %>% filter(outcome == "discharge"),
    
    slab = paste(trial),
    method = "REML"
  )

priors_noninvasive =
  rma(
    # Outcome
    measure = "RD", # risk difference
    
    # Tocilizumab group
    ai = events_toci,
    n1i = total_toci,
    
    # Control group
    ci = events_control,
    n2i = total_control,
    
    data = priors_noninvasive_raw %>% filter(outcome == "discharge"),
    
    slab = paste(trial),
    method = "REML"
  )

priors_invasive =
  rma(
    # Outcome
    measure = "RD", # risk difference
    
    # Tocilizumab group
    ai = events_toci,
    n1i = total_toci,
    
    # Control group
    ci = events_control,
    n2i = total_control,
    
    data = priors_invasive_raw %>% filter(outcome == "discharge"),
    
    slab = paste(trial),
    method = "REML"
  )
```

## Trials

# {.tabset .tabset-fade}

## Simple oxygen only {.panel-name}

```{r, fig.align='center', fig.height=4, fig.width=5}
forest(priors_simple_oxygen)
```

------------------------------------------------------------------------
  
## Non-invasive ventilation {.panel-name}
  
```{r, fig.align='center', fig.height=4, fig.width=5}
forest(priors_noninvasive)
```

------------------------------------------------------------------------
  
## Invasive mechanical ventilation {.panel-name}

```{r, fig.align='center', fig.height=4, fig.width=5}
forest(priors_invasive)
```

------------------------------------------------------------------------
  
# {-} 
  
## Priors
  
```{r}
## Extract mean and SD from rma() outputs

# Simple oxygen only
mean_prior_only = priors_simple_oxygen$beta
sd_prior_only = priors_simple_oxygen$se

# Non-invasive ventilation
mean_prior_noninvasive = priors_noninvasive$beta
sd_prior_noninvasive = priors_noninvasive$se

# Invasive mechanical ventilation
mean_prior_invasive = priors_invasive$beta
sd_prior_invasive = priors_invasive$se

table_prior =  tibble(
  
  "Subgroup" = c(
    "Simple oxygen only",
    "Non-invasive ventilation",
    "Invasive mechanical ventilation"
  ),
  
  "Number of trials" = c(
    priors_simple_oxygen_raw %>%
      filter(outcome == "discharge") %>%
      count() %>% pull(),
    priors_noninvasive_raw %>%
      filter(outcome == "discharge") %>%
      count() %>% pull(),
    priors_invasive_raw %>%
      filter(outcome == "discharge") %>%
      count() %>% pull()
  ),
  
  "Total number of patients" = c(
    priors_simple_oxygen_raw %>%
      filter(outcome == "discharge") %>%
      summarise(n = sum(total_control + total_toci)) %>% pull(),
    priors_noninvasive_raw %>%
      filter(outcome == "discharge") %>%
      summarise(n = sum(total_control + total_toci)) %>% pull(),
    priors_invasive_raw %>%
      filter(outcome == "discharge") %>%
      summarise(n = sum(total_control + total_toci)) %>% pull()
  ),
  
  "Mean RD" = c(
    round(mean_prior_only, 3),
    round(mean_prior_noninvasive, 3),
    round(mean_prior_invasive, 3)
  ),
  
  "SD" = c(
    round(sd_prior_only, 3),
    round(sd_prior_noninvasive, 3),
    round(sd_prior_invasive, 3)
  ),
  
  "Pr(< -5%)" = c(
    round(pnorm(-0.05, mean_prior_only, sd_prior_only), 2) * 100,
    round(pnorm(-0.05, mean_prior_noninvasive, sd_prior_noninvasive), 2) * 100,
    round(pnorm(-0.05, mean_prior_invasive, sd_prior_invasive), 2) * 100
  ),
  
  "Pr(< -2%)" = c(
    round(pnorm(-0.02, mean_prior_only, sd_prior_only), 2) * 100,
    round(pnorm(-0.02, mean_prior_noninvasive, sd_prior_noninvasive), 2) * 100,
    round(pnorm(-0.02, mean_prior_invasive, sd_prior_invasive), 2) * 100
  ),
  
  "Pr(< -1%)" = c(
    round(pnorm(-0.01, mean_prior_only, sd_prior_only), 2) * 100,
    round(pnorm(-0.01, mean_prior_noninvasive, sd_prior_noninvasive), 2) * 100,
    round(pnorm(-0.01, mean_prior_invasive, sd_prior_invasive), 2) * 100
  ),
  
  "Pr(> 0%)" = c(
    round((1 - pnorm(0, mean_prior_only, sd_prior_only)), 2) * 100,
    round((1 - pnorm(0, mean_prior_noninvasive, sd_prior_noninvasive)), 2) * 100,
    round((1 - pnorm(0, mean_prior_invasive, sd_prior_invasive)), 2) * 100
  ),
  
  "Pr(> 1%)" = c(
    round((1 - pnorm(0.01, mean_prior_only, sd_prior_only)), 2) * 100,
    round((1 - pnorm(0.01, mean_prior_noninvasive, sd_prior_noninvasive)), 2) * 100,
    round((1 - pnorm(0.01, mean_prior_invasive, sd_prior_invasive)), 2) * 100
  ),
  
  "Pr(> 2%)" = c(
    round((1 - pnorm(0.02, mean_prior_only, sd_prior_only)), 2) * 100,
    round((1 - pnorm(0.02, mean_prior_noninvasive, sd_prior_noninvasive)), 2) * 100,
    round((1 - pnorm(0.02, mean_prior_invasive, sd_prior_invasive)), 2) * 100
  ),
  
  "Pr(> 5%)" = c(
    round((1 - pnorm(0.05, mean_prior_only, sd_prior_only)), 2) * 100,
    round((1 - pnorm(0.05, mean_prior_noninvasive, sd_prior_noninvasive)), 2) * 100,
    round((1 - pnorm(0.05, mean_prior_invasive, sd_prior_invasive)), 2) * 100
  )
)

# Use kableExtra to have a nice table

table_prior %>% 
  kbl(booktabs = T, align = 'c') %>% 
  kable_styling(bootstrap_options = "striped", full_width = T) %>%
  column_spec(9, bold = T, color = "#65A37E") %>%
   add_header_above(c(" " = 5,
                     "Probability of Harm" = 3,
                     "Probability of Benefit" = 4)) %>% 
  footnote(general = "RD = Risk Difference; SD = Standard Deviation")
```


```{r, fig.align='center', fig.height=3.5, fig.width=9, fig.cap="Interval bars depict 50% and 95% credible intervals"}
### Plotting
set.seed = 123 # set seed for reproducibility (rnorm())
n = 10e4 # sampling size

# Assure subgroup order
# https://stackoverflow.com/questions/12774210/
# how-do-you-specifically-order-ggplot2-x-axis-instead-of-alphabetical-order

level_order = c("Invasive mechanical ventilation",
                "Non-invasive ventilation",
                "Simple oxygen only")

# Generate random normal distributed samples

tibble(
  "Simple oxygen only" = rnorm(n,
                               mean = mean_prior_only,
                               sd = sd_prior_only
  ),
  "Non-invasive ventilation" = rnorm(n,
                                     mean = mean_prior_noninvasive,
                                     sd = sd_prior_noninvasive
  ),
  "Invasive mechanical ventilation" = rnorm(n,
                                            mean = mean_prior_invasive,
                                            sd = sd_prior_invasive
  )
) %>%
  
  # make it tidy for ggplot
  pivot_longer(
    cols = c("Simple oxygen only":"Invasive mechanical ventilation"),
    names_to = "dist", values_to = "samples"
  ) %>%
  
  # Plot!
  ggplot(aes(x = 100 * samples, y = factor(dist, level = level_order))) +
  stat_halfeye(aes(fill = stat(x > 0)),
               .width = c(0.5, 0.95)
  ) +
  scale_fill_manual(values = c("gray80", "#65A37E")) +
  labs(x = "\nRisk difference (%)", y = "") +
  scale_x_continuous(breaks = seq(from = -20, to = 25, 5)) +
  scale_y_discrete(
    expand = c(0, .2)
  ) +
  theme(
    axis.ticks.x = element_blank(),
    axis.ticks.y = element_blank(),
    panel.background = element_blank(),
    panel.grid.major.x = element_line(color = "gray80", size = 0.3),
    legend.position = "none",
    plot.margin = margin(10, 10, 25, 10)
  ) +
  coord_cartesian(xlim = c(-20, 25))
```

<br><br>

```{r echo=TRUE}
sessionInfo()
```
