---
title: "posterior-probabilities"
author: "Arthur"
date: "4/19/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse) # data wrangling and plotting
library(tidybayes) # to plot distributions
library(ggdist)
library(patchwork) # to arrange multiple plots
library(here) # to find file paths within R project
library(metafor) # to summarize data for prior

# Function to generate posterior probability
source(here("final_analyses", "script", "functions", # file path
            "conjugate_normal_posterior.R"))
```

```{r}
data = 
  tibble(
    study = c("CRASH-2 (2011)", "Yut et al (2013)", "NCT (2019)", "CRASH-3 (2019)"),
    placebo_death = c(24, 18, 50, 525),
    placebo_n = c(137, 120, 285, 3757),
    TA_death = c(14, 12, 93, 485),
    TA_n = c(133, 120, 603, 3880)
  ) %>% 
  mutate(placebo_diff = placebo_n - placebo_death,
         TA_diff      = TA_n - TA_death)

data
```

```{r, fig.height= 2.5, fig.width=5}

set.seed = 123 # set seed for reproducibility (rbeta() function)

n = 10e4

# Filter in CRASH-3
crash3 = data %>% 
  filter(study == "CRASH-3 (2019)")

# Generate random beta distributions from data
# Assuming a non-informative prior beta(1,1) to use Bayesian inference 
crash3_beta = crash3 %>%

  # create random samples from data, Assuming a non-informative prior beta(1,1)
  #to use Bayesian inference
  
  summarise(control = list(rbeta(n, placebo_death + 1, placebo_diff + 1)),
            TA = list(rbeta(n, TA_death + 1, TA_diff + 1))) %>% 
  unnest(control:TA)

# Plot!
crash3_beta %>%
  
    # make it tidy for ggplot
    pivot_longer(cols = c(control, TA),
                 names_to = "group", values_to = "samples") %>% 

    ggplot(aes(x=100*samples, y = fct_rev(group))) + 
  
    # https://mjskay.github.io/ggdist/articles/slabinterval.html
    stat_halfeye(.width = 0.95,
                 aes(
                   fill = group,
                   fill_ramp = stat(cut_cdf_qi(
                     cdf,
                     .width = c(.5, 1),
                     labels = scales::percent_format()
                   ))
                 ),
                 position = "dodge",
                ) +
    # a range from 1 down to 0.2 ensures the fill goes dark to light inside-out
    # and doesn't get all the way down to white (0) on the lightest color
    scale_fill_ramp_discrete(range = c(1, 0.4), na.translate = FALSE) +
    scale_fill_manual(values = c("gray50", "firebrick3")) +
  
    labs( x = "\nMortality risk (%)", y  = "",
          title = "CRASH-3 trial\n") +
    scale_x_continuous(breaks = seq(from = 1, to = 17, 1)) +
    scale_y_discrete(labels=c("control" = "Control ",
                              "TA" = "Tranexamic\nAcid "),
                     expand = c(0,0.3)) +
  
    theme(axis.ticks.x = element_blank(),
          axis.ticks.y = element_blank(),
          panel.background = element_blank(),
          panel.grid.major.x = element_line(color = "gray80", size = 0.3),
          plot.title.position = 'plot',
          legend.position = "none",
          plot.margin = margin(20, 25, 15, 20))
```

```{r, fig.width=5, fig.height=2}
p1 = crash3_beta %>% 
  
  # Calculate difference between groups
  summarise(delta = 100*(TA - control)) %>% 
  
  # Plot!
  ggplot(aes(delta)) +
  
  # https://mjskay.github.io/ggdist/articles/slabinterval.html
   stat_halfeye(.width = 0.95,
               fill = "#4880B8") +
  
    labs(x = "\nMortality risk difference (%)", y  = "Density") +
    scale_x_continuous(breaks = seq(from = -4, to = 1, 1)) +
    scale_y_discrete(breaks = NULL,
                     expand = c(0,.03)) +
  theme(axis.ticks.x = element_blank(),
        #axis.ticks.y = element_blank(),
        panel.background = element_blank(),
        panel.grid.major.x = element_line(color = "gray80", size = 0.3),
        legend.position = "none")
```

```{r}
p2 = crash3_beta %>% 
  
  # Calculate difference between groups
  summarise(delta = TA - control) %>% 

  # Plot!
  ggplot(aes(100*delta)) +
  stat_ecdf(geom = "step") +
  labs(x = "\nMortality risk difference (%)",
       y  = "Probability RD \u2264 X") +
  scale_x_continuous(breaks = seq(from = -4, to = 1, .5),
                     limits = c(-4, 1)) +
  scale_y_continuous(breaks = seq(from = 0, to = 1, .1),
                     expand = c(0,.03)) +
  theme(axis.ticks.x = element_blank(),
        panel.background = element_blank(),
        panel.grid.major.x = element_line(color = "gray80", size = 0.3),
        panel.grid.major.y = element_line(color = "gray80", size = 0.3),
        plot.title.position = 'plot',
        legend.position = "none",
        )
```

```{r, fig.width=6, fig.height=3}
p1 + p2 + plot_annotation(
  title = "CRASH-3 trial",
  subtitle = "Risk difference between tranexamic acid and control groups"
)
```

```{r}
priors = data %>% 
  filter(study != "CRASH-3 (2019)")

priors_effects = 
    
    rma(
    
    # TA
    ai = TA_death,
    n1i = TA_n, 
    
    # control
    ci = placebo_death,
    n2i = placebo_n,
    
    data = priors,
    measure = "RD", # risk difference
    
    slab=paste(study), method="REML"
    
                     ) 

forest(priors_effects)
```

```{r}


# Normal approximation
crash3_normal = crash3 %>%
  summarise(
    # Standard deviation
    # sqrt(var); var = a*b/((a+b)^2 * (a + b + 1))

    # https://modelassist.epixanalytics.com/display/EA/Normal+approximation+to+the+Beta+distribution
    # https://en.wikipedia.org/wiki/Beta_distribution
    sd_control = sqrt(
      (placebo_death * placebo_diff) / (
        ((placebo_death + placebo_diff)^2) *
          (placebo_death + placebo_diff + 1)
      )
    ),
    sd_TA = sqrt(
      (TA_death * TA_diff) / (
        ((TA_death + TA_diff)^2) *
          (TA_death + TA_diff + 1)
      )
    ),
    sd_delta = sqrt(sd_control^2 + sd_TA^2),

    # Mean

    mean_delta = (TA_death / TA_n) - (placebo_death / placebo_n),
  )

# Put data (likelihood) + prior together
data_prior = tibble(
  data.mean = crash3_normal %>% pull(mean_delta),
  data.var = (crash3_normal %>% pull(sd_delta))^2,
  prior.mean = priors_effects$beta,
  prior.var = (priors_effects$se)^2
)

# Get the parameters of posterior distribution
posterior = data_prior %>% 
  nest(data.mean:prior.var) %>% 
  
  # Apply the function file loaded along with the packages
  mutate(posterior = pmap(data_prior, post.normal.mean)) %>%  
  unnest(posterior) %>% 
  as.tibble() %>%
  select("post.mean", "sqrt(post.var)") %>% 
  rename("post.sd" = "sqrt(post.var)")

# Create a single tibble with mean and SD of data, prior, and posterior pp
data_prior_posterior = data_prior %>% 
  summarise(data.mean = data.mean,
         data.sd = sqrt(data.var),
         prior.mean = prior.mean,
         prior.sd = sqrt(prior.var)) %>% 
  bind_cols(posterior)
  

```

```{r, fig.height= 3, fig.width=5}
set.seed = 123 # set seed for reproducibility (rnorm() function)
n = 10e4

# Create distributions from random samples
distributions = 
  data_prior_posterior %>% 
  summarise(Data = list(rnorm(n,
                              mean = data.mean,
                              sd = data.sd)),
            Prior = list(rnorm(n,
                              mean = prior.mean,
                              sd = prior.sd)),
            Posterior = list(rnorm(n,
                              mean = post.mean,
                              sd = post.sd))) %>% 
  unnest(Data:Posterior)

# https://stackoverflow.com/questions/12774210/
# how-do-you-specifically-order-ggplot2-x-axis-instead-of-alphabetical-order

level_order = c("Posterior", "Data", "Prior")

distributions %>%
  
    # make it tidy for ggplot
    pivot_longer(cols = c(Data:Posterior),
                 names_to = "dist", values_to = "samples") %>% 
    # Assure order
    #mutate(dist = factor(dist, levels = c("prior", "data","posterior")))

    # Plot!
    ggplot(aes(x=100*samples, y = factor(dist, level = level_order))) + 
  
    # https://mjskay.github.io/ggdist/articles/slabinterval.html
    stat_halfeye(.width = 0.95,
                 aes(
                   fill = dist,
                   fill_ramp = stat(cut_cdf_qi(
                     cdf,
                     .width = c(.5, 1),
                     labels = scales::percent_format()
                   ))
                 ),
                 position = "dodge",
                ) +
    # a range from 1 down to 0.2 ensures the fill goes dark to light inside-out
    # and doesn't get all the way down to white (0) on the lightest color
    scale_fill_ramp_discrete(range = c(1, 0.4), na.translate = FALSE) +
    scale_fill_manual(values = c("#00a0d5",
                                 "#df8f43",
                                 "#364d55")) +
  
    labs( x = "\nMortality risk difference (%)", y  = "",
          title = "CRASH-3 trial and previous evidence\n") +
    scale_x_continuous(breaks = seq(from = -8, to = 1, 1)) +
    scale_y_discrete(expand = c(0,0.1)) +
  
    theme(axis.ticks.x = element_blank(),
          axis.ticks.y = element_blank(),
          panel.background = element_blank(),
          panel.grid.major.x = element_line(color = "gray80", size = 0.3),
          plot.title.position = 'plot',
          legend.position = "none",
          plot.margin = margin(20, 25, 15, 20)) +
  coord_cartesian(xlim = c(-9, 2))
        

```

```{r, fig.width=5, fig.height=2}
p1 = distributions %>% 
  
  # Plot!
  ggplot(aes(100*Posterior)) +
  
  # https://mjskay.github.io/ggdist/articles/slabinterval.html
   stat_halfeye(.width = 0.95,
               fill = "#df8f43") +
  
    labs(x = "\nMortality risk difference (%)", y  = "Density") +
    scale_x_continuous(breaks = seq(from = -4, to = 1, 1)) +
    scale_y_discrete(breaks = NULL,
                     expand = c(0,.03)) +
  theme(axis.ticks.x = element_blank(),
        #axis.ticks.y = element_blank(),
        panel.background = element_blank(),
        panel.grid.major.x = element_line(color = "gray80", size = 0.3),
        legend.position = "none")
```

```{r}
p2 = distributions %>% 

  # Plot!
  ggplot(aes(100*Posterior)) +
  stat_ecdf(geom = "step") +
  labs(x = "\nMortality risk difference (%)",
       y  = "Probability RD \u2264 X") +
  scale_x_continuous(breaks = seq(from = -4, to = 1, .5),
                     limits = c(-4, 1)) +
  scale_y_continuous(breaks = seq(from = 0, to = 1, .1),
                     expand = c(0,.03)) +
  theme(axis.ticks.x = element_blank(),
        panel.background = element_blank(),
        panel.grid.major.x = element_line(color = "gray80", size = 0.3),
        panel.grid.major.y = element_line(color = "gray80", size = 0.3),
        plot.title.position = 'plot',
        legend.position = "none",
        )
```

```{r, fig.width=6, fig.height=3}
p1 + p2 + plot_annotation(
  title = "Posterior distribution - CRASH-3 and previous evidence",
  subtitle = "Risk difference between tranexamic acid and control groups"
)
```

```{r}
p1 = distributions %>% 
  
  # Plot!
  ggplot(aes(100*Posterior)) +
  
  # https://mjskay.github.io/ggdist/articles/slabinterval.html
   stat_halfeye(.width = 0.95,
               fill = "#df8f43") +
  
    labs(x = "\nNumber needed to treat (NNT)", y  = "Density") +
    scale_x_continuous(breaks = seq(from = -4, to = 0, 1),
                       labels = c("-4" = "25",
                                  "-3" = "33",
                                  "-2" = "50",
                                  "-1" = "100",
                                  "0" = "\u221E")) +
    scale_y_discrete(breaks = NULL,
                     expand = c(0,.03)) +
  theme(axis.ticks.x = element_blank(),
        #axis.ticks.y = element_blank(),
        panel.background = element_blank(),
        panel.grid.major.x = element_line(color = "gray80", size = 0.3),
        legend.position = "none") +
   coord_cartesian(xlim = c(-4, 0))
```

```{r}
p2 = distributions %>% 

  # Plot!
  ggplot(aes(100*Posterior)) +
  stat_ecdf(geom = "step") +
  labs(x = "\nNumber needed to treat (NNT)",
       y  = "Probability NNT \u2264 X") +
  scale_x_continuous(breaks = seq(from = -4, to = 0, 0.5),
                     limits = c(-4, 1),
                     labels = c("-4" = "25",
                                "-3.5" = "29",
                                "-3" = "33",
                                "-2.5" = "40",
                                "-2" = "50",
                                "-1.5" = "67",
                                "-1" = "100",
                                "-0.05" = "200",
                                "0" = "\u221E")) +
  scale_y_continuous(breaks = seq(from = 0, to = 1, .1),
                     expand = c(0,.03)) +
  theme(axis.ticks.x = element_blank(),
        panel.background = element_blank(),
        panel.grid.major.x = element_line(color = "gray80", size = 0.3),
        panel.grid.major.y = element_line(color = "gray80", size = 0.3),
        plot.title.position = 'plot',
        legend.position = "none",
        ) +
   coord_cartesian(xlim = c(-4, 0))
```

```{r, fig.width=6, fig.height=3}
p1 + p2 + plot_annotation(
  title = "Posterior distribution - CRASH-3 and previous evidence",
  subtitle = "Mortality risk difference between tranexamic acid and placebo"
)
```